// Import required functions from Redux Toolkit Query
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Base URL of your backend server
const BACKEND_URL = "https://aidf-stayquest-backend-shibishwar.onrender.com";

// Create the API service using RTK Query
export const api = createApi({
    // Optional name for the reducer slice
    reducerPath: "api",

    // Configure the base query with base URL and headers
    baseQuery: fetchBaseQuery({
        baseUrl: `${BACKEND_URL}/api/`,

        // Specify the tag types used for cache management
        tagTypes: ["Bookings"],

        // Add authorization token to headers for protected routes
        prepareHeaders: async (headers, { getState }) => {
            const token = await window?.Clerk?.session?.getToken();
            console.log(token); // Log token for debugging (remove in production)
            if (token) {
                headers.set("Authorization", `Bearer ${token}`);
            }
        },
    }),

    // Define endpoints (queries and mutations)
    endpoints: (builder) => ({
        // Query to get hotels based on filters (location, price, sort)
        getHotels: builder.query({
            query: ({ location, priceRange, sort }) => {
                const params = new URLSearchParams();

                if (location) params.append("location", location);
                if (priceRange) {
                    params.append("minPrice", priceRange[0]);
                    params.append("maxPrice", priceRange[1]);
                }
                if (sort) params.append("sort", sort);

                return `hotels?${params.toString()}`;
            },
        }),

        // Query to search hotels based on a search query string
        getHotelsForSearchQuery: builder.query({
            query: ({ query }) => `hotels/search/retrieve?query=${query}`,
        }),

        // Query to fetch a hotel by its ID
        getHotelById: builder.query({
            query: (id) => `hotels/${id}`,
        }),

        // Mutation to create a new hotel
        createHotel: builder.mutation({
            query: (hotel) => ({
                url: "hotels",
                method: "POST",
                body: hotel,
            }),
        }),

        // Mutation to create a booking
        createBooking: builder.mutation({
            query: (booking) => ({
                url: "bookings",
                method: "POST",
                body: booking,
            }),
            // Invalidate bookings cache to refresh the data after mutation
            invalidatesTags: ["Bookings"],
        }),

        // Query to get bookings for the currently logged-in user
        getUserBookings: builder.query({
            query: () => `bookings/user`,
            // Provides tag for cache to allow invalidation when needed
            providesTags: ["Bookings"],
        }),

        // Mutation to delete a booking by ID
        deleteBooking: builder.mutation({
            query: (bookingId) => ({
                url: `bookings/${bookingId}`,
                method: "DELETE",
            }),
            // Invalidate bookings cache after deletion
            invalidatesTags: ["Bookings"],
        }),
    }),
});

// Export hooks automatically generated by RTK Query
export const {
    useGetHotelsQuery,
    useGetHotelsForSearchQueryQuery,
    useGetHotelByIdQuery,
    useCreateHotelMutation,
    useCreateBookingMutation,
    useGetUserBookingsQuery,
    useDeleteBookingMutation,
} = api;
